@echo off
cd /d "%~dp0"
echo Starting Shadowdork dev server...
start "Shadowdork Server" cmd /c "npm run dev"
echo Waiting for server to initialize...
timeout /t 2 >nul
echo Opening game in default browser...
start "" http://localhost:5173
